---
# tasks file for nginx

- name: Add an nginx signing key, will not download if present
  become: yes
  apt_key:
    id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: add nginx repository
  become: yes
  apt_repository:
    repo: deb http://nginx.org/packages/mainline/ubuntu/ {{ ansible_distribution_release }} nginx
    state: present
    filename: nginx

- name: install nginx
  become: yes
  apt:
    name: nginx
    state: latest

- name: Enable service nginx, and set running state
  become: yes
  service:
    name: nginx
    enabled: yes
    state: started

- name: Create nginx conf dirs
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  with_items:
    - /etc/nginx/conf.d
    - /etc/nginx/conf.sites.d
    - /etc/nginx/sites

- name: Create nginx configs
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "/etc/nginx/{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_filetree:  templates/
  when: item.state == 'file'
  notify: reload nginx

