---

- name: Update ufw sysctl
  become: yes
  template: 
    src: sysctl.conf.j2 
    dest: /etc/ufw/sysctl.conf 
    owner: root 
    group: root 
    mode: 0644
  notify: reload ufw


- name: Update ufw default
  become: yes
  template: 
    src: ufw.j2 
    dest: /etc/default/ufw 
    owner: root 
    group: root 
    mode: 0644
  notify: reload ufw
